### ISSUE TITLE
"B_clean" cannot be found

### ISSUE THREAD

**Issue by oreopie** [uestctensorgroup/FastDeRain#1]
Thanks for sharing this code regarding video rain streak removal. It works on my rain video and it seems the most effective method that I have ever known. However, in your demo code, the variable "B_clean" might be not in the loaded .mat file. 
BTW, could you kindly share the editable core function "FastDeRain" as well as the GPU one? This may benefit the readers' understanding of the papers.

**Comment by TaiXiangJiang** [comment]
Thanks for your reminding. I have fixed this problem. Now the "B_clean" is
in the file "foreman_clean.mat" and the data for the demo
"Demo_FastDeRain_Oblique.m"
is also available.
As for the function FastDeRain.m and FastDeRain_GPU.m, I am not able to
share them with you since that our paper has not been officially published.
We will release them as soon as the acceptance of our article from a
journal.

Best

2018-03-22 15:10 GMT+08:00 littlesesame <notifications@github.com>:

**Comment by oreopie** [comment]
Thanks all the same. Looking forward to your journal version.
